### ISSUE TITLE
Problem: Python 3.5 myhdl 0.9.0 with starargs and kwargs 

### ISSUE THREAD

**Issue by mpflaga** [jandecaluwe/myhdl#148]
Python 3.5 using myhdl 0.9.0 has a new problem, whereas 3.4 does work. The jc2 and dff work just fine. I have not tried the others, just learning. Looks like others have the same problem; in that starargs and kwargs are gone in 3.5.

Not being even close to an expert or novice, I do make a **suggestion below**, based off of another bug tickets elsewhere. It seems to work. Not completely understanding it. But it might likely be just outright skipping the self.raised Error's. Not sure, so likely need another way to deal with that. Or actually may be what is intended.

```
mpflaga@mpflaga-VirtualBox:~/Desktop/myhdl/StopWatch$ python3.4 StopWatch.py
mpflaga@mpflaga-VirtualBox:~/Desktop/myhdl/StopWatch$ python3.5 StopWatch.py
Traceback (most recent call last):
  File "StopWatch.py", line 35, in <module>
    convert()
  File "StopWatch.py", line 32, in convert
    toVerilog(StopWatch, tens_led, ones_led, tenths_led, startstop, reset, clock)
  File "/home/mpflaga/.local/lib/python3.5/site-packages/myhdl/conversion/_toVerilog.py", line 151, in __call__
    genlist = _analyzeGens(arglist, h.absnames)
  File "/home/mpflaga/.local/lib/python3.5/site-packages/myhdl/conversion/_analyze.py", line 164, in _analyzeGens
    v.visit(tree)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/mpflaga/.local/lib/python3.5/site-packages/myhdl/conversion/_analyze.py", line 290, in visit_FunctionDef
    self.visitList(node.body)
  File "/home/mpflaga/.local/lib/python3.5/site-packages/myhdl/conversion/_misc.py", line 162, in visitList
    self.visit(n)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/mpflaga/.local/lib/python3.5/site-packages/myhdl/conversion/_analyze.py", line 261, in visit_Assign
    self.visit(node.value)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 255, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/usr/lib/python3.5/ast.py", line 255, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/home/mpflaga/.local/lib/python3.5/site-packages/myhdl/conversion/_analyze.py", line 264, in visit_Call
    if node.starargs:
AttributeError: 'Call' object has no attribute 'starargs'
mpflaga@mpflaga-VirtualBox:~/Desktop/myhdl/StopWatch$
```

**suggested quick work-a-round:**

```
--- C:\Python35\Lib\site-packages\myhdl\conversion\_analyze.py.bak	2016-02-22 00:07:07.000000000 -0500   
+++ C:\Python35\Lib\site-packages\myhdl\conversion\_analyze.py	2016-02-22 00:08:15.000000000 -0500   
@@ -258,15 +258,15 @@   
         if len(node.targets) > 1:   
             self.raiseError(node, _error.NotSupported, "multiple assignments")   
         self.visit(node.targets[0])   
         self.visit(node.value)   
    
     def visit_Call(self, node):   
-        if node.starargs:   
+        if getattr(node, 'starargs', None):   
             self.raiseError(node, _error.NotSupported, "extra positional arguments")   
-        if node.kwargs:   
+        if getattr(node, 'kwargs', None):   
             self.raiseError(node, _error.NotSupported, "extra named arguments")   
         # f = eval(_unparse(node.node), self.tree.symdict)   
         self.generic_visit(node)   
    
     def visit_Compare(self, node):   
         if len(node.ops) != 1:   
```

**Comment by mpflaga** [comment]
Ok, so it is already fixed in your latest repo.
Should have checked that first.
